### ISSUE TITLE
ci: adding a check-docker job in CI.

### ISSUE THREAD

**Issue by xiao-jay** [RocksLabs/kvrocks-operator#29]
Suggest adding a check-docker job in CI.
```
  check-docker:
    name: Check Docker image
    needs: [lint-build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: false
```
from https://github.com/RocksLabs/kvrocks-operator/pull/21#issuecomment-1563118024
